Improve the way we run builds.
- No need for `find_path_to_rspec_exe`; I've discovered that `--standalone`
  and `--binstubs` together produce bins that don't load bundler.
- Add `-x` to `set -e` as that will cause the script to print each command
  as it runs.  No need for `print_and_run`.
- Add cucumber to test_all script, and use just that for the build.

diff --git a/script/test_all b/script/test_all
--- a/script/test_all
+++ b/script/test_all
@@ -1,28 +1,26 @@
 #!/bin/bash
 
-function print_and_run {
-  echo $1
-  ($1)
-}
-
-set -e
+set -e -x
 
 echo "Bundling Standalone so we can run the specs w/o bundler loaded"
 
-bundle install --standalone
-path_to_rspec_exe=`script/find_path_to_rspec_exe`
-
-command_prefix="ruby -w -r./bundle/bundler/setup.rb -S $path_to_rspec_exe"
+bundle install --standalone --binstubs
 
 echo "Running all..."
 
-print_and_run "$command_prefix spec --format progress --profile"
+bin/rspec spec --format progress --profile
 
 echo
 echo "--------------------------------------------------------------------"
 echo
 
 for file in `find spec -iname '*_spec.rb'`; do
-  print_and_run "$command_prefix $file --format progress"
+  bin/rspec $file --format progress
 done
+
+# TODO: it would be nice to figure out how to run the cukes w/o the overhead of
+# bundler, but just running `bin/cucumber` can fail due to the fact that it
+# shells out (via aruba) and executes `rspec`--which can pick up the wrong
+# rspec version if we're not running with bundler.
+bundle exec cucumber
 
